### ISSUE TITLE
BSOD in ATIKMDAG.SYS

### ISSUE THREAD

**Issue by sunscreen** [nicehash/NiceHashMiner-Archived#65]
Intel Core i5 4670
8GB RAM
AMD R7 7700 2 GB 
Windows 8.1 Pro

-Tried clean install of OS
-Tried all drivers
-Still persists like the one from the matrix even with the latest Nicehash 
-SGminer 5.2 works in seperate mining software
-6000 series gpu working just fine with 2 GB!
-5000 series gpu working just fine with 1 GB!

please fix !!!!!!!

**Comment by theLosers106** [comment]
I am not sure what GPU that is .. is it the AMD 7770? and please provide more details such as what you are trying to mine and when does the crash happen.. BSOD is usually caused by overclocking or undervolting or unstable driver..

**Comment by sunscreen** [comment]
Sorry mate, the 7770. Typo. The GPU driver crashes as soon as a benchmark is attempted.

**Comment by sunscreen** [comment]
Hello thelooser106 sorry for the reply in error there ..confusion was reigning supreme .. sorry I have a few different AMD gpus.. so this is the gpu in question .. I know its not due to a unstable driver as I have tried all the drivers possible (including the recommended 15.7.1 version) and each time removed cleanly with DDU and also the card runs happily under sgMiner **5.2**.

Strangely enough I cant find this card with 1 GB any where .. in fact the only card that comes up which resemble the physical characteristic of this card is the R7 7750 which does have 2 GB of ram ..

http://xfxforce.com/en-us/products/all-previous-gpus/amd-radeon-hd-7750-core-edition-fx-775a-cgfv
see my gpu-z  screen shot..

regardless of the memory it should still work as the 5000 series also has only 1 GB and that works

![gpuz](https://cloud.githubusercontent.com/assets/1124068/14244652/24912620-fa54-11e5-8a6b-03b4d266736c.gif)

**Comment by sunscreen** [comment]
http://xfxforce.com/en-us/products/all-previous-gpus/amd-radeon-hd-7750-core-edition-fx-775a-znj4

all makes sense now .. hopefully we might see a fix ;)

**Comment by theLosers106** [comment]
Have you tried to run using runme.bat in the sgminer-5-3-0-general folder manually?

**Comment by theLosers106** [comment]
and one more info that would be helpful is what versions did you actually tried when you said 

> Tried all drivers

Thanks

**Comment by sunscreen** [comment]
Hi thelooser106 .. just waiting for a current round of mining to complete 17:22 GMT.. then I will have a look at this  7750 one last time as I have a little nvidia GT740 to replace it with failing that ... as I mentioned I've tried allot of different drivers the recommended ones I tried where crimson based and from there every thing from the newest to reallllly old! .. I am semi sure its not even a driver a issue..   and I always ddu to remove them to keep things clean as possible .. one thing is certain the default and current clock on that card do not seem to be sane so the new sgminer might be upsetting the gpu with the derived setting .. but If you get this before later I will post back asap :)

**Comment by theLosers106** [comment]
okay.. try running it manually first by using the runme.bat and post back your findings.. (:

**Comment by sunscreen** [comment]
hey there, yeah running with runme.bat still bsod's

**Comment by sunscreen** [comment]
well that is a shame, as a gaming card it performs ok and never crashed on any game, i know mining is more about the opencl/compute programs and clock and ram speed also play a part.. but the cards now going to have to be condemned to sgMiner 5.2 or I might just donate to a developer or a young budding gamer in need some where

**Comment by cduncan41** [comment]
Had this problem here is how I fixed it
Control Panel -> Hardware/Sound -> Power Options (Control What Power Button Does) -> Change settings currently unavailable -> Deselect Fast Startup -> Save Changes. 

Hope this works, spent 2 days messing with registry, drivers and dos. This fixed it right away. Good luck man.

**Comment by sunscreen** [comment]
Wow thanks @cduncan41 :) will give that a try in a little while and shout you back my results

**Comment by sunscreen** [comment]
@cduncan41 unfortunately that solution did not work in my case

**Comment by sunscreen** [comment]
I realized one thing about this problem is that even when the R7770 is present and I attempt mine on another AMD gpu it still crashes the system its presence alone causes the crash even if its not the card that is mining eg: if I put in my 6000 or 5000 and deselect the 7000 the system still crashes.. utter night mare this is .. always more questions then answers

**Comment by cduncan41** [comment]
Dang, I had hoped this would fix it for you. It did it this same thing to me on my ASUS R9 380 Strix cards. It never did it with my Sapphire 390x's. The only difference between the rigs is the 380's have a celeron dual core and my 390 has an i5. Did you try and copy the kernel files from the general folder into your users/appdata/temp folder? 

Also, I couldn't get it to work at all with 16.xx drivers. Hashrates were bad everywhere else too. I had to try catalyst 15.2 and 15.7 I stuck with 15.7 after using a GPU driver removal.

**Comment by nicehashdev** [comment]
Please, use latest version and reopen if you still have issues with this.

**Comment by gminton86** [comment]
I’m having this exact same issue and cannot fix it I’ve tried everything it’s been over 2 months now I need help
