### ISSUE TITLE
"Setting up miners"

### ISSUE THREAD

**Issue by MooMilo** [nicehash/NiceHashMiner-Archived#685]
I have downloaded v1.7.5.1, but when I open it, it goes through a few steps, and then freezes on the "Setting up miners" part.  I'm running Windows 10 on a Vaio with an Intel i3 350M processor.  What is gong on?
![image](https://cloud.githubusercontent.com/assets/22922533/23343175/cc4f0122-fc2c-11e6-96b2-8a63b600223c.png)

**Comment by S74nk0** [comment]
@MooMilo To bypass this you can manually download the miner files and unzip them directly to the NHM folder. But just to be clear where it is failing post the log file (it would be best if you run a clean install just to see where it is stopping). Anti Virus false positives are usually the reason for this.

**Comment by S74nk0** [comment]
There were AWS issues and this was probably related. 

Closing issue as this should be fixed

**Comment by visnar** [comment]
Nicehash hangs!
I 've tried also with the newest version of NiceHashMiner

Version=1
EventType=AppHangB1
EventTime=131363761629392350
ReportType=1
Consent=1
UploadTime=131363761631267561
ReportIdentifier=6996fbf5-1e98-11e7-8234-448500813e8a
IntegratorReportIdentifier=6996fbf6-1e98-11e7-8234-448500813e8a
WOW64=1
NsAppName=NiceHashMiner.exe
Response.BucketId=6ea8b317afa6f796896b80c211384a5c
Response.BucketTable=5
Response.LegacyBucketId=129415476809
Response.type=4
Sig[0].Name=Ime programa
Sig[0].Value=NiceHashMiner.exe
Sig[1].Name=Različica programa
Sig[1].Value=1.7.5.8
Sig[2].Name=Časovni žig programa
Sig[2].Value=58ebc843
Sig[3].Name=Podpis neodzivanja
Sig[3].Value=96ce
Sig[4].Name=Vrsta neodzivanja
Sig[4].Value=67247360
DynamicSig[1].Name=Različica operacijskega sistema
DynamicSig[1].Value=10.0.10586.2.0.0.256.48
DynamicSig[2].Name=Področne nastavitve
DynamicSig[2].Value=1060
DynamicSig[22].Name=Dodatni podpis neodzivanja 1
DynamicSig[22].Value=96ce20ff8a8ca6c490d0d3d31c8599c0
DynamicSig[23].Name=Dodatni podpis neodzivanja 2
DynamicSig[23].Value=fb2e
DynamicSig[24].Name=Dodatni podpis neodzivanja 3
DynamicSig[24].Value=fb2e7ed8c3f42f7c4ea31a8e6642797e
DynamicSig[25].Name=Dodatni podpis neodzivanja 4
DynamicSig[25].Value=96ce
DynamicSig[26].Name=Dodatni podpis neodzivanja 5
DynamicSig[26].Value=96ce20ff8a8ca6c490d0d3d31c8599c0
DynamicSig[27].Name=Dodatni podpis neodzivanja 6
DynamicSig[27].Value=fb2e
DynamicSig[28].Name=Dodatni podpis neodzivanja 7
DynamicSig[28].Value=fb2e7ed8c3f42f7c4ea31a8e6642797e
UI[3]=NiceHashMiner se ne odziva
UI[4]=Če zaprete program, lahko izgubite podatke.
UI[5]=Zapri program
UI[6]=Zapri program
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Se je prenehal odzivati in se zaprl
ConsentKey=AppHangXProcB1
AppName=NiceHashMiner
AppPath=C:\Program Files\NiceHashMiner_v1.7.5.7\NiceHashMiner.exe
ReportDescription=Zaradi težave je program prenehal delovati s sistemom Windows.
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=72C2E4CDFED59B3FE93E9C2D23307822

**Comment by gergesh** [comment]
Leaving this here for future use - if your NiceHash miner is in 'C:\ Program Files\' or any other protected dir, either move it or open as an administrator.

**Comment by dinicthis** [comment]
1.8 does the same. I've white listed it in Bitdefender, run it as administrator. What is wrong with your software?

You still have not answered the question, or provided any solutions.

**Comment by Bernitall** [comment]
Tryng to run 1.8.1.6 and the issue is still happening.
And after repeated attempts over the last 8 hours I'm just done with this crap.
- Not running it in any system folder, I have put it first on my secondary internal SSD, then on an external HDD.
- I've run as admin, I've tried tinkering with permissions, I've whitelisted every damned file that came up in BitDefender and finally even disabled BitDefender alltogether, I've checked and re-checked and manually whitelisted everything in the folder in my firewall.
- I've manually downloaded the 3rd-party bin zip, unzipped - only to hae the Not-So-NiceHash miner simply start downloading everything by itself again, and again hanging at 99.98% (it always hangs at that exact point, with one exception where it hung at 99.97%).

The log isn't showing anything bad (only thing that stands out is "[INFO] [ADL] ADL fan getting failed with error code -8") - not even when after hanging for a while, NHML simply CTD's.
I'm on an AMD CPU and GPU, and the site says NHM2 doesn't support AMD GPU's - well, apparently neither does NHML.
The only good thing is that it actually recognizes my GPU right off the bat, but that gets negated by it not doing any mining at all... more like a NiceHashPaperweight.

In fact, looking at the log it's like NHML itself is finished with the setting up of the miners but for some reason the miner downloader/setup isn't getting that message or something.

**Comment by dinicthis** [comment]
your hardware might be unsupported now. a 980 just quit being supported
that one guy I know has.

too-slow hardware is being edged out by nice hash.

On Jan 15, 2018 8:35 PM, "Bernitall" <notifications@github.com> wrote:

Tryng to run 1.8.1.6 and the issue is still happening.
And after repeated attempts over the last 8 hours I'm just done with this
crap.

   - Not running it in any system folder, I have put it first on my
   secondary internal SSD, then on an external HDD.
   - I've run as admin, I've tried tinkering with permissions, I've
   whitelisted every damned file that came up in BitDefender and finally even
   disabled BitDefender alltogether, I've checked and re-checked and manually
   whitelisted everything in the folder in my firewall.
   - I've manually downloaded the 3rd-party bin zip, unzipped - only to hae
   the Not-So-NiceHash miner simply start downloading everything by itself
   again, and again hanging at 99.98% (it always hangs at that exact point,
   with one exception where it hung at 99.97%).

The log isn't showing anything bad - not even when after hanging for a
while, NHML simply CTD's.
I'm on an AMD CPU and GPU, and the site says NHM2 doesn't support AMD -
well, apparently neither does NHML.
The only good thing is that it actually recognizes my GPU right off the
bat, but that gets negated by it not doing any mining at all... more like a
NiceHashPaperweight.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nicehash/NiceHashMiner/issues/685#issuecomment-357851502>,
or mute the thread

**Comment by Bernitall** [comment]
Well, they shouldn't be doing the CPU/GPU thing at all then, just say "fuck off if you haven't at least got a Baikal Giant B"then. And they should've kicked Intel CPU's to the curb well before AMD CPU's then, as my AMD CPU out-mines my brother's two flashy sparkly new Intels for several coins.
Anyway, I'm done with dealing with an issue in their software that's been around for at least a year, which they choose to ignore across all versions.
